### PR TITLE
Update docs and fix 404 issue due to duplicate slash

### PR DESCRIPTION
**Pull request by hypr2771**

### CODE REVIEW

**Comment by derekhe** [comment]
it works, please merge

**Comment by brennebeck** [comment]
I've also validated this. The 404 issue is fixed and everything appears to be in working order again.

**Comment by ttpro1995** [comment]
confirm pull request https://github.com/nicohaenggi/SafariBooks-Downloader/pull/40  fixed 404

**Comment by hypr2771** [comment]
Hi @yaasin12.
The 404 issue should be fixed Indeed.
If not, you can either discuss it here or on my forked project hypr2771/SafariBooks-Downloader.
Sorry for not linking directly to projects, phone is really a pain when it comes to multi tabs.

Thanks @yaasin12 !

**Comment by ferdous-al-quraeshi** [comment]
@nicohaenggi 
**404 is fixed**.
I suggest you to review and test the solution and merge this pull asap _(you can see lots of people are getting results!)_ :hourglass_flowing_sand: 

@hypr2771 
Thanks for the solution :1st_place_medal:

**Comment by jzytnyk-korewireless** [comment]
glad to see someone already had a fix for my 404 issue!   thanks @hypr2771

**Pull request merged**
